org: rajivmehtaflex
app: gsqswithpython
service: sqs-experiments
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

custom:
  pythonRequirements:
    dockerizePip: true

constructs:
  jobs:
    type: queue
    worker:
      handler: handler.consumer

functions:
  producer:
    handler: handler.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}

plugins:
  - serverless-lift
  - serverless-python-requirements
package:
  patterns:
    - '!node_modules/**'
