
name: base flow

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: BranchV1
          
      - name: Check version info text
        run: cat version_info.txt

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
